<template>
    <div id="app">
      <router-view/>
    </div>
  </template>
  
  <script>
  export default 
  {
    name: 'App'
  }
  </script>
  
  <!-- <style>
  
  <script>
  export default 
  {
    name: '@/LoginPage/Login'
  }
  </script>
  
  <style> -->
  
  #app 
  {
    font-family: 'Century Gothic';
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 40px;
  }
  #app a
  {
  font-size: 30px;
  }
  </style>
  